name: Terraform Backend Setup

on:
  workflow_dispatch:

jobs:
  backend:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Terraform Init
      working-directory: terraform/backend
      run: terraform init

    - name: Terraform Apply
      working-directory: terraform/backend
      run: terraform apply -auto-approve
